{% set version = '1.2.3' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-lambda.r
  version: {{ version|replace("-", "_") }}

source:
  fn: lambda.r_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/lambda.r_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/lambda.r/lambda.r_{{ version }}.tar.gz
  sha256: 0cd8e37ba1a0960888016a85d492da51a57df54bd65ff920b08c79a3bfbe8631

build:
  merge_build_host: True  # [win]
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-formatr
  run:
    - r-base
    - r-formatr

test:
  commands:
    - $R -e "library('lambda.r')"           # [not win]
    - "\"%R%\" -e \"library('lambda.r')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=lambda.r
  license: LGPL-3
  summary: A language extension to efficiently write functional programs in R. Syntax extensions
    include multi-part function definitions, pattern matching, guard statements, built-in
    (optional) type safety.
  license_family: LGPL

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
