{% set version = "1.2.4" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-lambda.r
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/lambda.r_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/lambda.r/lambda.r_{{ version }}.tar.gz
  sha256: d252fee39065326c6d9f45ad798076522cec05e73b8905c1b30f95a61f7801d6

build:
  merge_build_host: True  # [win]
  number: 2
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-formatr
  run:
    - r-base
    - r-formatr

test:
  commands:
    - $R -e "library('lambda.r')"           # [not win]
    - "\"%R%\" -e \"library('lambda.r')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=lambda.r
  license: LGPL-3.0-only
  summary: A language extension to efficiently write functional programs in R. Syntax extensions
    include multi-part function definitions, pattern matching, guard statements, built-in
    (optional) type safety.
  license_family: LGPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/LGPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
