appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: YF5jwXreEZT0jqPcsE5PKMVSHKJ4TTiP1YYk5IGRLAx3cox7yxwwqbhqUwZ8avjri6r0utwUtEM4/9ZgQW4vUn9+H1hiQKgvFlDkEDc+4WXyJuTOAwkPrsmsYOfJNBO0EOh26pEKnKxhUwGCE0HQf5rtwajBGseDn+YfPgI8gvM4m4lV8nNoW/ZUTNkslyNcDvtz2B5a1KUg4awLeXPnUPhfFpsVY78bZ+TpFwcX/nwlA6Abte0HwijLJfIaafAtQA2HfnUtEU4PuQkv4cW3BZGPRr0OTh6zfn3NhUHLfcwgbK0PydLhH0xVyDIcEqmXGDkChdzn1Ak8uQqB9pVLU+jTB7NiRSQmy9wWjB2k5gpXVMb0EmKHm1zoIy1BlnezTvM2+14edqbC+KpH5OQF7TEjNsJJYfR2YUfM22KhcuOGAEyok0xNJaaBIVs064tpjvGjQ0e/V6A+8PKpGS3yndzQngVvO+fLu+xC4xyAMKvK8F7PyqILBMR/OSpf1CiYyUr22O4B4R+i3jpC1p63tovBWFZyoajaqWL7CKe3HiyxN1sdMcxitv5URBoEfeSoCHV0jXvc2kLHYM1GMol4wGIXEboyj6TIfAx3+yXDrmj7BLyfmygcE2wvqjf7zPklh+t+bKx9gbLt2q14+KYGV6dKIDwnDBCmZlHElZ8j+Kk=}
